parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64

- name: pool
  type: string
  values:
  - sonicbld
  - sonicbld_8c
  - sonicbld-arm64
  - sonicbld-armhf
  default: sonicbld

- name: timeout
  type: number
  default: 600

- name: sonic_slave
  type: string

- name: artifact_name
  type: string

jobs:
- job:
  pool: ${{ parameters.pool }}
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}

  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}:latest

  steps:
  - checkout: self
    clean: true
    displayName: 'Checkout code'
  - script: |
      git config --global user.email "lguohan@build.com"
      git config --global user.name "Guohan Lu"
      export kernel_procure_method=build
      cat /proc/cpuinfo
      CONFIGURED_ARCH=${{ parameters.arch }} make
    displayName: "Compile sonic kernel"
  - publish: $(System.DefaultWorkingDirectory)/
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive sonic kernel debian packages"
